### ISSUE TITLE
Wrong outputs generated ?

### ISSUE THREAD

**Issue by shiftlabs1** [serverless-stack/serverless-stack#1695]
Hi, I rand the svelte-app example in this repository and the output i got is not as expected. The example 's stack has an API and a static site . but the output i got is 
```
Stack dev-svelte-app-debug-stack
  Status: deployed
  Outputs:
    BucketArn: arn:aws:s3:::dev-svelte-app-debug-stack-bucket83908e77-f5dlrm73tbfy
    BucketName: dev-svelte-app-debug-stack-bucket83908e77-f5dlrm73tbfy
    Endpoint: wss://5bgi6ytou4.execute-api.us-east-1.amazonaws.com/dev
```
What am i missing ? from the documentation, this was supposed to be something like 
```
Stack dev-svelte-app-my-stack
  Status: deployed
  Outputs:
    ApiEndpoint: https://sez1p3dsia.execute-api.ap-south-1.amazonaws.com
    SiteUrl: https://d2uyljrh4twuwq.cloudfront.net
```
