### ISSUE TITLE
Can't use a "catch-all" Api route 

### ISSUE THREAD

**Issue by claudioc** [serverless-stack/serverless-stack#207]
I am not sure which side is at fault here, but within a SAM template I am able to create a path such as this one (anything that starts with `e`:

```yaml
      Events:
        Api:
          Type: Api
          Properties:
            Path: /e{id}
            Method: GET
```

The use-case is very limited an I could use something like `/e/{id}` instead, but I wonder if there is way to use a "crazy" wildcard like it is possible in SAM.

When I try doing the same using `sst.Api` with this configuration:
```typescript
    const api = new sst.Api(this, "Api", {
      routes: {
        "GET /e{id}": "src/get.handler"
      },
```

my stack "fails" with this error:
`Error: One or more path parts appear to be invalid. Parts are validated against this regular expression: ^(\{[\w.-]+\+?\}|[a-zA-Z0-9._-]+)$ (Service: AmazonApiGatewayV2; Status Code: 400; Error Code: BadRequestException; Request ID: 50763f3f-9ca2-4f1e-95f9-d4cxxxxx; Proxy: null)`
