### ISSUE TITLE
Hide CloudFormation outputs and exports used created by CDK internally

### ISSUE THREAD

**Issue by fwang** [serverless-stack/serverless-stack#665]
[Sam Hulick on Slack](https://serverless-stack.slack.com/archives/C01JG3B20RY/p1628469461280600) mentioned this is what is defined in his app:
```
    this.addOutputs({
      BastionHostId: bastionHost.instanceId,
      BastionHostZone: bastionHost.instanceAvailabilityZone,
      UserPoolId: auth.cognitoUserPool!.userPoolId,
    });
```
But this is what's been shown:
```
Outputs:
    BastionHostBastionHostIdC743CBD6: xx
    BastionHostId: xx
    BastionHostZone: us-east-1a
    ExportsOutputRefUserPool6BA7E5F296FD7236: xx
    ExportsOutputRefUserPoolClient2F5918F753847A55: xx
    UserPoolId: xx
```

Let's hide the outputs/exports created by CDK

Jay added that:
> Just had another thought about this. How about when we use the verbose flag we print all the excess CDK outputs as well?
